In [4]:
import datasets
import pandas as pd

ds = datasets.load_dataset("lukebarousse/data_jobs")
df = ds["train"].to_pandas()

# 1 - Viewing data

In [6]:
# selecting top rows

df[["job_title", "search_location", "job_country"]].head(3)

,job_title,search_location,job_country
0,Senior Clinical Data Engineer / Principal Clin...,"Texas, United States",United States
1,Data Analyst,Mexico,Mexico
2,"Data Engineer/Scientist/Analyst, Mid or Senior...",Germany,Germany

In [8]:
# selecting bottom rows

df[["job_title_short", "salary_year_avg", "job_skills"]].tail(3)

,job_title_short,salary_year_avg,job_skills
785738,Business Analyst,NaN,"['powerpoint', 'excel']"
785739,Data Engineer,NaN,"['python', 'go', 'nosql', 'sql', 'mongo', 'she..."
785740,Software Engineer,NaN,"['aws', 'flow']"

In [ ]:
# selecting rows and columns without the loc and iloc methods

df[["job_title_short", "salary_year_avg", "job_skills"]][100:201]

,job_title_short,salary_year_avg,job_skills
100,Data Scientist,228222.0,"['sql', 'r', 'python', 'express']"
101,Data Analyst,NaN,['sql']
102,Data Scientist,NaN,"['python', 'sql', 'r', 'java']"
103,Data Engineer,NaN,"['sql', 'nosql', 'aws', 'gcp', 'azure', 'spark..."
104,Software Engineer,NaN,"['c++', 'java', 'snowflake']"
...,...,...,...
196,Data Engineer,NaN,"['sql', 'visual basic', 'sql server', 'tableau']"
197,Data Analyst,NaN,"['sql', 'python', 'java', 'scala', 'snowflake'..."
198,Data Engineer,NaN,['aws']
199,Data Scientist,NaN,"['go', 'sql', 'python', 'windows']"
200,Data Scientist,NaN,['aws']

In [11]:
# iloc method

df[["job_title_short", "salary_year_avg", "job_location"]].iloc[100:201]

,job_title_short,salary_year_avg,job_location
100,Data Scientist,228222.0,"Mountain View, CA"
101,Data Analyst,NaN,Singapore
102,Data Scientist,NaN,"Rome, Metropolitan City of Rome Capital, Italy"
103,Data Engineer,NaN,Anywhere
104,Software Engineer,NaN,"Berlin, Germany"
...,...,...,...
196,Data Engineer,NaN,Luxembourg
197,Data Analyst,NaN,Anywhere
198,Data Engineer,NaN,Hong Kong
199,Data Scientist,NaN,Anywhere
200,Data Scientist,NaN,"Foster City, CA"

# 2 - Gathering superficial data insights

In [ ]:
# info method, retrives general data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [14]:
# describe method, returns basic information on the numeric columns of the dataframe
df.describe()

       salary_year_avg  salary_hour_avg
count     22003.000000     10662.000000
mean     123286.274072        47.016598
std       48312.449482        21.890738
min       15000.000000         8.000000
25%       90000.000000        27.500000
50%      115000.000000        45.980000
75%      150000.000000        61.159996
max      960000.000000       391.000000

# 3 - Filtering data

In [38]:
filtered_df_1 = df[["job_title_short", "job_location", "salary_year_avg"]][(df["job_title_short"] == "Data Analyst") & (df["salary_year_avg"].notna())]
filtered_df_1

       job_title_short                 job_location  salary_year_avg
109       Data Analyst                     Anywhere          89000.0
180       Data Analyst                Dos Palos, CA          90250.0
410       Data Analyst           Atlantic Beach, FL         133285.0
988       Data Analyst              Springfield, MA          62623.0
1413      Data Analyst                  Atlanta, GA          71300.0
...                ...                          ...              ...
784033    Data Analyst   Mumbai, Maharashtra, India         111175.0
784423    Data Analyst     Juriquilla, Qro., Mexico          80850.0
784882    Data Analyst                   Denton, TX          87500.0
785187    Data Analyst             Lisbon, Portugal         111175.0
785515    Data Analyst  Bengaluru, Karnataka, India         105000.0

[5451 rows x 3 columns]

In [45]:
filtered_df_2 = df.loc[
    (df["job_title_short"] == "Data Analyst") & (df["salary_year_avg"].notna()),
    ["job_title_short", "job_location", "salary_year_avg"]
]
filtered_df_2

       job_title_short                 job_location  salary_year_avg
109       Data Analyst                     Anywhere          89000.0
180       Data Analyst                Dos Palos, CA          90250.0
410       Data Analyst           Atlantic Beach, FL         133285.0
988       Data Analyst              Springfield, MA          62623.0
1413      Data Analyst                  Atlanta, GA          71300.0
...                ...                          ...              ...
784033    Data Analyst   Mumbai, Maharashtra, India         111175.0
784423    Data Analyst     Juriquilla, Qro., Mexico          80850.0
784882    Data Analyst                   Denton, TX          87500.0
785187    Data Analyst             Lisbon, Portugal         111175.0
785515    Data Analyst  Bengaluru, Karnataka, India         105000.0

[5451 rows x 3 columns]