In [3]:
import pandas as pd
from datasets import load_dataset

# load data
ds = load_dataset("lukebarousse/data_jobs")
df = ds["train"].to_pandas()

# clean data
df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

## Indexing Methods

df.index\
set_index()\
sort_index()\
reset_index()

In [6]:
# recovering the indexes from a dataframe

df.index

RangeIndex(start=0, stop=785741, step=1)

In [ ]:
# data frame does not have an index name

df.sample(1)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
245252,Data Analyst,Data Analyst,"Kuala Lumpur, Federal Territory of Kuala Lumpu...",via Maukerja,NaN,False,Malaysia,2023-10-11 07:27:55,True,False,Malaysia,NaN,NaN,NaN,Wedialab Sdn Bhd,"['sql', 'python', 'excel', 'sheets', 'tableau']","{'analyst_tools': ['excel', 'sheets', 'tableau..."

In [8]:
df.index.name = "job_index"
df.sample(1)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
365598,Cloud Engineer,Aws Cloud Engineer Expert,Nigeria,via Emprego.pt,Full-time,False,Nigeria,2023-02-17 23:42:31,True,False,Nigeria,NaN,NaN,NaN,Expectoo,"['python', 'c#', 'mongodb', 'mongodb', 'c++', ...","{'cloud': ['aws'], 'databases': ['mongodb', 'm..."

In [15]:
# reset_index - resets the indexes of the dataframe and creates a new column with the old indexes

job_postings_brazil = df.loc[
    df["job_country"] == "Brazil",
    :
].reset_index()

job_postings_brazil.rename(columns={"job_index":"job_index_old"}, inplace=True)
job_postings_brazil.index.name = "job_index"

job_postings_brazil.sample(1)

,job_index_old,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,,
3475,365279,Cloud Engineer,Engenheiro de Dados Azure Synapse SENIOR,"Barueri, State of São Paulo, Brazil",via LinkedIn,Full-time,False,Brazil,2023-07-25 23:17:49,True,False,Brazil,NaN,NaN,NaN,Yssy & Co.,"['python', 'sql', 'azure', 'pyspark']","{'cloud': ['azure'], 'libraries': ['pyspark'],..."

In [17]:
# set_index() - replaces the current indexes with a column from the dataframe

job_postings_brazil.set_index("job_index_old", inplace=True)
job_postings_brazil.index.name = "job_index"

job_postings_brazil.head(3)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
14,Data Engineer,Data Engineer,"Rio de Janeiro, State of Rio de Janeiro, Brazil",via BeBee,Full-time,False,Brazil,2023-07-13 13:17:51,False,False,Brazil,NaN,NaN,NaN,Oowlish,"['mongodb', 'mongodb']","{'databases': ['mongodb'], 'programming': ['mo..."
55,Data Scientist,Data Scientist,"São Paulo, State of São Paulo, Brazil",via BeBee,Full-time,False,Brazil,2023-01-03 23:02:27,False,False,Brazil,NaN,NaN,NaN,Mars,"['python', 'sql', 'azure']","{'cloud': ['azure'], 'programming': ['python',..."
84,Data Scientist,Data Science,Brazil,via BeBee,Full-time,False,Brazil,2023-01-23 13:20:12,False,False,Brazil,NaN,NaN,NaN,Pfizer,"['python', 'r', 'sql', 'javascript', 'aws', 's...","{'cloud': ['aws', 'snowflake'], 'libraries': [..."

In [21]:
# sort_index() - sorts the dataframe rows based on the indexes

yearly_salary_analysis = df.pivot_table(index="job_title_short", values="salary_year_avg", aggfunc=["median", "min", "max"])
yearly_salary_analysis.sort_index(inplace=True)

yearly_salary_analysis

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  85000.0         16500.0        387460.0
Cloud Engineer                    90000.0         42000.0        280000.0
Data Analyst                      90000.0         25000.0        650000.0
Data Engineer                    125000.0         15000.0        525000.0
Data Scientist                   127500.0         27000.0        960000.0
Machine Learning Engineer        106415.0         30000.0        325000.0
Senior Data Analyst              111175.0         30000.0        425000.0
Senior Data Engineer             147500.0         35000.0        425000.0
Senior Data Scientist            155500.0         45000.0        890000.0
Software Engineer                 99150.0         28000.0        375000.0

In [22]:
yearly_salary_analysis.sort_values(by=("median", "salary_year_avg"), ascending=False)

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Senior Data Scientist            155500.0         45000.0        890000.0
Senior Data Engineer             147500.0         35000.0        425000.0
Data Scientist                   127500.0         27000.0        960000.0
Data Engineer                    125000.0         15000.0        525000.0
Senior Data Analyst              111175.0         30000.0        425000.0
Machine Learning Engineer        106415.0         30000.0        325000.0
Software Engineer                 99150.0         28000.0        375000.0
Cloud Engineer                    90000.0         42000.0        280000.0
Data Analyst                      90000.0         25000.0        650000.0
Business Analyst                  85000.0         16500.0        387460.0